name: ml_basics
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10.11
  - numpy=1.23.5
  - matplotlib=3.7.1
  - scipy=1.10.1
  - seaborn=0.12.2
  - scikit-learn=1.2.2
  - torchvision=0.13.1
  - torchmetrics=0.11.2
  - tqdm=4.65.0
  - Pillow=10.0.1
  - safetensors==0.4.2
  - pandas=2.1.1
  - pip
  - pip:
      - torchmetrics==0.11.2
      - torcheval
      - pytorch_lightning==2.2
      - Pillow
      - einops
      - wandb
      - timm==0.6.13